# Generated by Django 5.0.3 on 2024-03-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_alter_facultades_cantgrupos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='facultad',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Gestion.facultades'),
        ),
    ]
